# Generated by Django 5.2.15 on 2026-06-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('image', models.ImageField(upload_to='productiondata')),
                ('i_mean', models.FloatField()),
                ('i_std', models.FloatField()),
                ('pred_mean', models.JSONField()),
                ('pred_std', models.JSONField()),
                ('pred_alpha', models.JSONField()),
            ],
        ),
    ]
