# Generated by Django 5.2.15 on 2026-06-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxy',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
