# Generated by Django 5.2.7 on 2025-11-06 12:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_galaxy_pred_alpha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxy',
            name='pred_alpha',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=3),
        ),
    ]
