# Generated by Django 5.2.7 on 2025-11-06 12:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_galaxy_pred_alpha'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxy',
            name='pred_mean',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=0, size=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galaxy',
            name='pred_std',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=0, size=3),
            preserve_default=False,
        ),
    ]
