# Generated by Django 5.2.7 on 2025-11-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_galaxy_pred_mean_galaxy_pred_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxy',
            name='pred_alpha',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='galaxy',
            name='pred_mean',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='galaxy',
            name='pred_std',
            field=models.JSONField(),
        ),
    ]
